### PR TITLE
feat: add `parenStyle` option to configuration

### LINKED ISSUE #2: Add a setting to have the implicit parentheses displayed like the explicit parentheses
I would prefer to have implicit parentheses to have the same scale and position as the explicit parentheses.
At the moment, the implicit parentheses are scaled down and lowered down which I don't like. It is a source of confusion to distinguish between the implicit closing parentheses and commas.

### PR DESCRIPTION
**Pull request by aleclarson**
Closes #2

### CODE REVIEW

**Comment by captbaritone** [comment]
Thanks! At first glance this looks good. One thought I had was, should the config option be big/small, or should the user be able to supply the actual characters that they want to use?

Curious to hear your thoughts on that approach. Is it worth expanding that flexibility to users?

**Comment by aleclarson** [comment]
I thought about it while implementing, and I think there could be a `parenCharacters` option added in the future if such functionality is desired, but I doubt it will be, to be honest. I'd be fine with changing `tiny` to `small` if you prefer. :)

**Comment by captbaritone** [comment]
I was on the fence about it, and your reasoning seems... reasonable. Let's go with this! Thanks for the contribution! I'll try to publish a new version in the next few days.

**Comment by captbaritone** [comment]
Published as version 1.1.0 https://marketplace.visualstudio.com/items?itemName=JordanEldredge.implicit-parentheses

**Comment by captbaritone** [comment]
@aleclarson I just realized there's one missing piece here. When a user changes this config, we should ensure we rerender the parens. I think that might be as simple as including `PAREN_STYLE_CONFIG ` in this condition here: https://github.com/captbaritone/vscode-implicit-parentheses/blob/master/src/extension.ts#L41

Do you think you could look at adding that?

**Pull request merged**
